gems: [bourbon, neat, jekyll-assets]

# Structure configuration
source: ./source
destination: ./build

# Site settings
title: UC Santa Cruz - Fifty ways to be amazing
email: pio@ucsc.edu
description: In honor of the campus's 50th year — here are 50 ways to become just as amazing as UC Santa Cruz.
url: "http://www.ucsc.edu" # the base hostname & protocol for your site

baseurl: "/50-ways"

permalink: "/:title/"
timezone: America/Los_Angeles

# Build settings
exclude: ['.gitignore', 'Gemfile', 'Gemfile.lock', 'Guardfile', '.asset-cache', '/source/.asset-cache', '.scss-lint.yml']

# Build settings
markdown: rdiscount
rdiscount:
  extensions: [smart]