# Site settings
title: UC Santa Cruz - Fifty ways to be amazing
email: pio@ucsc.edu
description: In honor of the campus's 50th year — here are 50 ways to become just as amazing as UC Santa Cruz.
url: "http://0.0.0.0:4000" # the base hostname & protocol for your site
twitter_username: ucsc
github_username:  ucsc

timezone: America/Los_Angeles

permalink: /:title

# Build settings
markdown: rdiscount
rdiscount:
  extensions: [smart]

encoding: 'utf-8'
